---
global:
  evaluation_interval: 30s

scrape_configs:
 - job_name: docker
   ec2_sd_configs:
    - region: us-west-2
      port: 9323
   relabel_configs: &ec2_relabel_configs
     - target_label: instance
       regex: '(.+)'
       source_labels: [__meta_ec2_tag_Name]

     - target_label: environment
       regex: '(.+)'
       source_labels: [__meta_ec2_tag_Environment]

     - target_label: az
       regex: '(.+)'
       source_labels: [__meta_ec2_availability_zone]

 - job_name: cadvisor
   ec2_sd_configs:
    - region: us-west-2
      port: 8080
   relabel_configs: *ec2_relabel_configs
