---
- hosts: all
  gather_facts: false
  pre_tasks:
    - name: install python 3
      raw: sudo apt-get -y install python3
  
- hosts: all
  tasks:
  - import_role:
      name: geerlingguy.docker
    vars:
      docker_package: 'docker-ce=5:18.09*'
      docker_install_compose: false
    become: true

  - name: Add the docker group
    group:
      name: docker
      gid: 999

  - name: Unlink docker from sudo requirement
    become: true
    shell: |
      sudo usermod -aG docker {{ ansible_ssh_user }}
  
  - name: Configure docker host
    become: true
    copy:
      content: |
        {
          "metrics-addr" : "0.0.0.0:9323",
          "experimental" : true,
          "log-opts" : {
            "max-size" : "1g"
          }
        }
      dest: /etc/docker/daemon.json
      mode: 0400

  - name: Reboot
    become: true
    reboot:

  - name: Install pip3
    become: true
    apt:
      name: 
        - python3-pip
        - python3-setuptools

  - name: Install Ansible docker dependencies
    pip:
      name: '{{ item.name }}'
      version: '{{ item.version }}'
    with_items:
      - name: docker-compose
        version: 1.22.0-rc1
      - name: docker
        version: 3.4.1
      - name: requests
        version: 2.21.0
