---
- set_fact:
    authority_list: '{{ hostvars["localhost"].authority_list | default([])}}'

- name: Template configs
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: node.toml
      dest: /tmp/node.toml
    - src: spec.json.j2
      dest: /tmp/spec.json

- name: Restart parity docker
  import_tasks: restart_parity_docker.yml

- name: Create account
  command: "curl --data '{\"jsonrpc\":\"2.0\",\"method\":\"parity_newAccountFromPhrase\",\"params\":[\"{{ account_passphrase }}\", \"{{ account_password }}\"],\"id\":0}' -H \"Content-Type: application/json\" -X POST localhost:{{ rpc_port }}"
  register: responce

- name: Get address
  set_fact:
    new_account: '{{ (responce.stdout | from_json)["result"] }}'

- name: Show account
  debug:
    var: new_account
